name: build-test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SBT Action
        uses: lokkju/github-action-sbt@v0.2.2
        with:
          commands: "debian:packageBin"
      - name: Archive VerCors .deb
        uses: actions/upload-artifact@v2
        with:
          name: vercors-debian-package
          retention-days: 1
          path: |
            target/**/*.deb
  test0:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download VerCors binary
        uses: actions/download-artifact@v2
        with:
          name: vercors-debian-package
      - run: dpkg -i ./target/*.deb
      - run: vercors --silicon examples/manual/fibonacci.pvl
      - run: SPLIT=0/2 vercors --test=examples --test-workers=1 --tool=silicon --exclude-suite=slow,medium,problem-fail,skip-travis
  test1:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download VerCors binary
        uses: actions/download-artifact@v2
        with:
          name: vercors-debian-package
      - run: dpkg -i ./target/*.deb
      - run: vercors --silicon examples/manual/fibonacci.pvl
      - run: SPLIT=1/2 vercors --test=examples --test-workers=1 --tool=silicon --exclude-suite=slow,medium,problem-fail,skip-travis
